/* Test program generated by ChatGPT to run the malloc intercepter */

#include <stdlib.h>
#include <stdio.h>

int main() {
    printf("Starting malloc tests...\n");

    // Test 1: Simple malloc
    char *str1 = malloc(10);
    printf("Allocated 10 bytes\n");

    // Test 2: Larger allocation
    int *arr = malloc(100 * sizeof(int));
    printf("Allocated %zu bytes for int array\n", 100 * sizeof(int));

    // Test 3: Small allocation
    char *str2 = malloc(5);
    printf("Allocated 5 bytes\n");

    // Test 4: Another allocation
    double *dbl = malloc(sizeof(double));
    printf("Allocated %zu bytes for double\n", sizeof(double));

    // Clean up
    free(str1);
    free(arr);
    free(str2);
    free(dbl);

    printf("Test completed.\n");
    return 0;
}
